<a href="https://colab.research.google.com/github/AsadBukhari886/foundations_of_artificial_neural_network/blob/main/Numpy_part_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Sort , Search & Counting function

In [1]:
import numpy as np



In [2]:
arr= np.array([4,3,3,5,6,72,3,3455,5,4,5,6])

In [3]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [4]:
np.sort(arr)

array([   3,    3,    3,    4,    4,    5,    5,    5,    6,    6,   72,
       3455])

In [5]:
np.searchsorted(arr, 34) # it will tell us 34 will be at 12 index posirion in a sorted order

np.int64(12)

In [6]:
arr1 = np.array([0,345, 345, 0,0,0,0,0,])

In [7]:
# count_nonzeor fun will tell us how many non zero values are in the data

np.count_nonzero(arr1)

2

In [8]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [9]:
np.where(arr > 6) # it will tell abou the index

(array([5, 7]),)

In [10]:
np.extract(arr>6 , arr) # now it will give the data values form the arr parameter

array([  72, 3455])

In [11]:
# Byte Swapping function

arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [12]:
arr.byteswap() # will convert the data into a bytes one by one

array([ 288230376151711744,  216172782113783808,  216172782113783808,
        360287970189639680,  432345564227567616, 5188146770730811392,
        216172782113783808, 9154973617514086400,  360287970189639680,
        288230376151711744,  360287970189639680,  432345564227567616])

## Copies & Views

In [13]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [14]:
a = np.copy(arr) #deep copy will occer

In [15]:
a

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [16]:
b = arr.view() # it same like shallow copy concept not new data position it will take same var data position

In [17]:
b = arr

In [18]:
b

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [19]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [20]:
b[0] = 65

In [21]:
b

array([  65,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [22]:
arr

array([  65,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

# Matrix Library

## matlib = Matrix Library

In [23]:
import numpy.matlib as nm

In [24]:
np.zeros(5) # it will create matrix

#not the array it will careate

array([0., 0., 0., 0., 0.])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#Linear Algebra

In [27]:
arr1 = np.random.randint([[2,3], [4,5]])

In [28]:
arr2 = np.random.randint([[5,3], [2,5]])

In [29]:
np.dot(arr1, arr2)

array([[ 1,  4],
       [12, 15]])

In [30]:
arr1@arr2

array([[ 1,  4],
       [12, 15]])